name: smartstruct_generator
description: smartstruct - A dart bean mapper annotation processor - the easy nullsafe way!
version: 1.2.7
homepage: https://github.com/smotastic/smartstruct
publish_to: https://dart.cloudsmith.io/netglade/netgladepub/
environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  source_gen_test: ^1.0.3
  test: ^1.21.4
dependencies:
  analyzer: ^4.4.0
  build: ^2.3.0
  code_builder: ^4.2.0
  path: ^1.8.1
  smartstruct: ^1.2.6
  source_gen: ^1.2.2
